# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21734cb896dc48920b4332573a6e67839913a092ea5d2bfe636da35bc10c57a8daf1e77e94b77889cb891f330e976ebc03b2a88b7f45757b148299c4c8d14383

test:
  secret_key_base: c506459a6c80c29cd1ef1ec882b2038ae6bf3cf9fd9f4febaf182238d3f75207f59785e97bd6f051feec83aed6e0bbcc54e6278936ef8620a087c0360f481142

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
